DROP SCHEMA IF EXISTS shop;
CREATE SCHEMA IF NOT EXISTS shop DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS shop.brand (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_brand` VARCHAR(45) NOT NULL UNIQUE ,
  PRIMARY KEY (`id`))
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS shop.model (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_model` VARCHAR(45) NOT NULL UNIQUE ,
  PRIMARY KEY (`id`))
DEFAULT CHARACTER SET = utf8;

